import type { NextPage } from 'next';
import dynamic from 'next/dynamic';
import Head from 'next/head';
import React from 'react';

import { Box, Container, Stack } from '@mui/material';

const WalletMultiButtonDynamic = dynamic(
    async () => (await import('@solana/wallet-adapter-material-ui')).WalletMultiButton,
    { ssr: false }
);

const Home: NextPage = () => {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <Container>
                <Stack my={2} spacing={2}>
                    <Box>
                        <WalletMultiButtonDynamic />
                    </Box>
                </Stack>
            </Container>
        </>
    );
};

export default Home;
